name: "Release_Workflow"

on:
  push:
    branches: [main]
    tags:
      - '1.1.1'
  pull_request:
    branches: [main]
  workflow_dispatch: # enable manual workflow runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'
      - name: Pull distroless base image
        run: docker pull gcr.io/distroless/base-debian10:v2
      - name: Conexion docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Create Docker image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./super_calculator
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mycalculatore

