name: "Link_Workflow"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install hadolint
        run: sudo apt-get install -y hadolint

      - name: Run hadolint analysis
        run: |
         docker run --rm -i hadolint/hadolint < ./super_calculator/Dockerfile
