name: semp_hado_linter

on:
  pull_request:
  push:
  workflow_dispatch:

jobs: 
 analyse-code:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Super-Linter
        if: github.event_name == 'pull_request'
        uses: github/super-linter@v4
        with:
          VALIDATE_ALL_CODEBASE: True
          
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build SuperCalculator_nelly
        run: go build -o super_calculator_nelly super_calculator/cmd/main.go
          
      - name: Run Semgrep on Go files
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/go"
          path: "docker run --rm -i docker.io/semgrep/semgrep:v0.63.0 < ./super_calculator/Dockerfile"
          
      - name: Run hadolint analysis
        run: |
         docker run --rm -i hadolint/hadolint < ./super_calculator/Dockerfile


