name: super_linter
on:
  pull_request:
    branches: [main]

jobs:
  super_linter:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Super-Linter
        uses: github/super-linter@v4

      - name: Run Super-Linter
        env:
          VALIDATE_ALL_CODEBASE: false
        run: /usr/bin/super-linter
